declare kanwa{
    input data_in9[BIT],data_in10[BIT],data_in11[BIT],data_in12[BIT],data_in13[BIT],data_in14[BIT],
data_in17[BIT],data_in18[BIT],data_in19[BIT],data_in20[BIT],data_in21[BIT],data_in22[BIT],
data_in25[BIT],data_in26[BIT],data_in27[BIT],data_in28[BIT],data_in29[BIT],data_in30[BIT],
data_in33[BIT],data_in34[BIT],data_in35[BIT],data_in36[BIT],data_in37[BIT],data_in38[BIT],
data_in41[BIT],data_in42[BIT],data_in43[BIT],data_in44[BIT],data_in45[BIT],data_in46[BIT],
data_in49[BIT],data_in50[BIT],data_in51[BIT],data_in52[BIT],data_in53[BIT],data_in54[BIT]
,start[BIT],goal[BIT]   ; 
    output data_out9[BIT],data_out10[BIT],data_out11[BIT],data_out12[BIT],data_out13[BIT],data_out14[BIT],
data_out17[BIT],data_out18[BIT],data_out19[BIT],data_out20[BIT],data_out21[BIT],data_out22[BIT],
data_out25[BIT],data_out26[BIT],data_out27[BIT],data_out28[BIT],data_out29[BIT],data_out30[BIT],
data_out33[BIT],data_out34[BIT],data_out35[BIT],data_out36[BIT],data_out37[BIT],data_out38[BIT],
data_out41[BIT],data_out42[BIT],data_out43[BIT],data_out44[BIT],data_out45[BIT],data_out46[BIT],
data_out49[BIT],data_out50[BIT],data_out51[BIT],data_out52[BIT],data_out53[BIT],data_out54[BIT]
;
            func_in in_do(data_in9,data_in10,data_in11,data_in12,data_in13,data_in14,
data_in17,data_in18,data_in19,data_in20,data_in21,data_in22,
data_in25,data_in26,data_in27,data_in28,data_in29,data_in30,
data_in33,data_in34,data_in35,data_in36,data_in37,data_in38,
data_in41,data_in42,data_in43,data_in44,data_in45,data_in46,
data_in49,data_in50,data_in51,data_in52,data_in53,data_in54,
            start,goal);
    func_out out_do(data_out9,data_out10,data_out11,data_out12,data_out13,data_out14,
data_out17,data_out18,data_out19,data_out20,data_out21,data_out22,
data_out25,data_out26,data_out27,data_out28,data_out29,data_out30,
data_out33,data_out34,data_out35,data_out36,data_out37,data_out38,
data_out41,data_out42,data_out43,data_out44,data_out45,data_out46,
data_out49,data_out50,data_out51,data_out52,data_out53,data_out54    );

} 
