declare kouka{
    input data_in9[BIT],data_in10[BIT],data_in11[BIT],data_in12[BIT],data_in13[BIT],data_in14[BIT],
data_in17[BIT],data_in18[BIT],data_in19[BIT],data_in20[BIT],data_in21[BIT],data_in22[BIT],
data_in25[BIT],data_in26[BIT],data_in27[BIT],data_in28[BIT],data_in29[BIT],data_in30[BIT],
data_in33[BIT],data_in34[BIT],data_in35[BIT],data_in36[BIT],data_in37[BIT],data_in38[BIT],
data_in41[BIT],data_in42[BIT],data_in43[BIT],data_in44[BIT],data_in45[BIT],data_in46[BIT],
data_in49[BIT],data_in50[BIT],data_in51[BIT],data_in52[BIT],data_in53[BIT],data_in54[BIT],
start[BIT],goal[BIT];
    output loot_out0[2],loot_out1[2],loot_out2[2],loot_out3[2],loot_out4[2],loot_out5[2],loot_out6[2],loot_out7[2],loot_out8[2],loot_out9[2],
            loot_out10[2],loot_out11[2],loot_out12[2],loot_out13[2],loot_out14[2],loot_out15[2],loot_out16[2],loot_out17[2],loot_out18[2],loot_out19[2],
            loot_out20[2],loot_out21[2],loot_out22[2],loot_out23[2],loot_out24[2],loot_out25[2],loot_out26[2],loot_out27[2],loot_out28[2],loot_out29[2],
            loot_out30[2],loot_out31[2],loot_out32[2],loot_out33[2],loot_out34[2],loot_out35[2],loot_out36[2],loot_out37[2],loot_out38[2],loot_out39[2],
            loot_out40[2],loot_out41[2],loot_out42[2],loot_out43[2],loot_out44[2],loot_out45[2],loot_out46[2],loot_out47[2],loot_out48[2],loot_out49[2],
            loot_out50[2],loot_out51[2],loot_out52[2],loot_out53[2],loot_out54[2],loot_out55[2],loot_out56[2],loot_out57[2],loot_out58[2],loot_out59[2];

    func_in in_do(data_in9,data_in10,data_in11,data_in12,data_in13,data_in14,
data_in17,data_in18,data_in19,data_in20,data_in21,data_in22,
data_in25,data_in26,data_in27,data_in28,data_in29,data_in30,
data_in33,data_in34,data_in35,data_in36,data_in37,data_in38,
data_in41,data_in42,data_in43,data_in44,data_in45,data_in46,
data_in49,data_in50,data_in51,data_in52,data_in53,data_in54,
								start,goal);
  func_out out_do(loot_out0,loot_out1,loot_out2,loot_out3,loot_out4,loot_out5,loot_out6,loot_out7,loot_out8,loot_out9,
            loot_out10,loot_out11,loot_out12,loot_out13,loot_out14,loot_out15,loot_out16,loot_out17,loot_out18,loot_out19,
            loot_out20,loot_out21,loot_out22,loot_out23,loot_out24,loot_out25,loot_out26,loot_out27,loot_out28,loot_out29,
            loot_out30,loot_out31,loot_out32,loot_out33,loot_out34,loot_out35,loot_out36,loot_out37,loot_out38,loot_out39,
            loot_out40,loot_out41,loot_out42,loot_out43,loot_out44,loot_out45,loot_out46,loot_out47,loot_out48,loot_out49,
            loot_out50,loot_out51,loot_out52,loot_out53,loot_out54,loot_out55,loot_out56,loot_out57,loot_out58,loot_out59
            );           
}
