declare meiro{
   input map_value_arg0[BIT],map_value_arg1[BIT],map_value_arg2[BIT],map_value_arg3[BIT],map_value_arg4[BIT],map_value_arg5[BIT],map_value_arg6[BIT],map_value_arg7[BIT],map_value_arg8[BIT],map_value_arg9[BIT]
                  ,map_value_arg10[BIT],map_value_arg11[BIT],map_value_arg12[BIT],map_value_arg13[BIT],map_value_arg14[BIT],map_value_arg15[BIT],map_value_arg16[BIT],map_value_arg17[BIT],map_value_arg18[BIT],map_value_arg19[BIT]
                  ,map_value_arg20[BIT],map_value_arg21[BIT],map_value_arg22[BIT],map_value_arg23[BIT],map_value_arg24[BIT],map_value_arg25[BIT],map_value_arg26[BIT],map_value_arg27[BIT],map_value_arg28[BIT],map_value_arg29[BIT]
                  ,map_value_arg30[BIT],map_value_arg31[BIT],map_value_arg32[BIT],map_value_arg33[BIT],map_value_arg34[BIT],map_value_arg35[BIT],map_value_arg36[BIT],map_value_arg37[BIT],map_value_arg38[BIT],map_value_arg39[BIT]
                  ,map_value_arg40[BIT],map_value_arg41[BIT],map_value_arg42[BIT],map_value_arg43[BIT],map_value_arg44[BIT],map_value_arg45[BIT],map_value_arg46[BIT],map_value_arg47[BIT],map_value_arg48[BIT],map_value_arg49[BIT]
                  ,map_value_arg50[BIT],map_value_arg51[BIT],map_value_arg52[BIT],map_value_arg53[BIT],map_value_arg54[BIT],map_value_arg55[BIT],map_value_arg56[BIT],map_value_arg57[BIT],map_value_arg58[BIT],map_value_arg59[BIT]
                  ,map_value_arg60[BIT],map_value_arg61[BIT],map_value_arg62[BIT],map_value_arg63[BIT];
   output  kekka_out0[2],kekka_out1[2],kekka_out2[2],kekka_out3[2],kekka_out4[2],kekka_out5[2],kekka_out6[2],kekka_out7[2],kekka_out8[2],kekka_out9[2],
                     kekka_out10[2],kekka_out11[2],kekka_out12[2],kekka_out13[2],kekka_out14[2],kekka_out15[2],kekka_out16[2],kekka_out17[2],kekka_out18[2],kekka_out19[2],
                     kekka_out20[2],kekka_out21[2],kekka_out22[2],kekka_out23[2],kekka_out24[2],kekka_out25[2],kekka_out26[2],kekka_out27[2],kekka_out28[2],kekka_out29[2],
                     kekka_out30[2],kekka_out31[2],kekka_out32[2],kekka_out33[2],kekka_out34[2],kekka_out35[2],kekka_out36[2],kekka_out37[2],kekka_out38[2],kekka_out39[2],
                     kekka_out40[2],kekka_out41[2],kekka_out42[2],kekka_out43[2],kekka_out44[2],kekka_out45[2],kekka_out46[2],kekka_out47[2],kekka_out48[2],kekka_out49[2],
                     kekka_out50[2],kekka_out51[2],kekka_out52[2],kekka_out53[2],kekka_out54[2],kekka_out55[2],kekka_out56[2],kekka_out57[2],kekka_out58[2],kekka_out59[2]
                    ;
   func_in in_do(map_value_arg0,map_value_arg1,map_value_arg2,map_value_arg3,map_value_arg4,map_value_arg5,map_value_arg6,map_value_arg7,map_value_arg8,map_value_arg9,
                  map_value_arg10,map_value_arg11,map_value_arg12,map_value_arg13,map_value_arg14,map_value_arg15,map_value_arg16,map_value_arg17,map_value_arg18,map_value_arg19,
                  map_value_arg20,map_value_arg21,map_value_arg22,map_value_arg23,map_value_arg24,map_value_arg25,map_value_arg26,map_value_arg27,map_value_arg28,map_value_arg29,
                  map_value_arg30,map_value_arg31,map_value_arg32,map_value_arg33,map_value_arg34,map_value_arg35,map_value_arg36,map_value_arg37,map_value_arg38,map_value_arg39,
                  map_value_arg40,map_value_arg41,map_value_arg42,map_value_arg43,map_value_arg44,map_value_arg45,map_value_arg46,map_value_arg47,map_value_arg48,map_value_arg49,
                  map_value_arg50,map_value_arg51,map_value_arg52,map_value_arg53,map_value_arg54,map_value_arg55,map_value_arg56,map_value_arg57,map_value_arg58,map_value_arg59,
                  map_value_arg60,map_value_arg61,map_value_arg62,map_value_arg63
                  );
   func_out end_meiro(kekka_out0,kekka_out1,kekka_out2,kekka_out3,kekka_out4,kekka_out5,kekka_out6,kekka_out7,kekka_out8,kekka_out9,
                     kekka_out10,kekka_out11,kekka_out12,kekka_out13,kekka_out14,kekka_out15,kekka_out16,kekka_out17,kekka_out18,kekka_out19,
                     kekka_out20,kekka_out21,kekka_out22,kekka_out23,kekka_out24,kekka_out25,kekka_out26,kekka_out27,kekka_out28,kekka_out29,
                     kekka_out30,kekka_out31,kekka_out32,kekka_out33,kekka_out34,kekka_out35,kekka_out36,kekka_out37,kekka_out38,kekka_out39,
                     kekka_out40,kekka_out41,kekka_out42,kekka_out43,kekka_out44,kekka_out45,kekka_out46,kekka_out47,kekka_out48,kekka_out49,
                     kekka_out50,kekka_out51,kekka_out52,kekka_out53,kekka_out54,kekka_out55,kekka_out56,kekka_out57,kekka_out58,kekka_out59
                     );

    }
