declare subs{
	input data_in9[BIT],data_in10[BIT],data_in11[BIT],data_in12[BIT],data_in13[BIT],data_in14[BIT],
data_in17[BIT],data_in18[BIT],data_in19[BIT],data_in20[BIT],data_in21[BIT],data_in22[BIT],
data_in25[BIT],data_in26[BIT],data_in27[BIT],data_in28[BIT],data_in29[BIT],data_in30[BIT],
data_index9[BIT],data_index10[BIT],data_index11[BIT],data_index12[BIT],data_index13[BIT],data_index14[BIT],
data_index17[BIT],data_index18[BIT],data_index19[BIT],data_index20[BIT],data_index21[BIT],data_index22[BIT],
data_index25[BIT],data_index26[BIT],data_index27[BIT],data_index28[BIT],data_index29[BIT],data_index30[BIT];
	output sub_array_out[BIT];
	func_in subs_exe(                   
data_index9,data_index10,data_index11,data_index12,data_index13,data_index14,
data_index17,data_index18,data_index19,data_index20,data_index21,data_index22,
data_index25,data_index26,data_index27,data_index28,data_index29,data_index30,
data_in9,data_in10,data_in11,data_in12,data_in13,data_in14,
data_in17,data_in18,data_in19,data_in20,data_in21,data_in22,
data_in25,data_in26,data_in27,data_in28,data_in29,data_in30);
}
